version: "3.1"
    
services:
  db:
    image: mysql:8.0
    container_name: morton-music-admin-db
    restart: always
    volumes:
      - ./db/migrate.sql:/docker-entrypoint-initdb.d/2.sql 
      - ./db/seed.sql:/docker-entrypoint-initdb.d/1.sql 
    environment:
      MYSQL_ROOT_PASSWORD: MYROOTPASSWORD
      MYSQL_USER: morton-music
      MYSQL_PASSWORD: morton-music
      MYSQL_DATABASE: morton-music
    ports:
      - "3306:3306"
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: morton-music-wordpress
    volumes:
      - ./src:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always
    environment:
      WP_DEBUG: true
      WP_DEBUG_DISPLAY: true
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: morton-music
      WORDPRESS_DB_PASSWORD: morton-music
      WORDPRESS_DB_NAME: morton-music
volumes:
  db_data:
  wordpress_data:
